// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package pnpiot.serializationperf;

public final class LocationProtobuf {
  private LocationProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pnpiot.serializationperf.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 timeStamp = 1;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required int64 timeStamp = 1;</code>
     */
    long getTimeStamp();

    /**
     * <code>required int32 fixType = 2;</code>
     */
    boolean hasFixType();
    /**
     * <code>required int32 fixType = 2;</code>
     */
    int getFixType();

    /**
     * <code>required int32 latitude = 3;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required int32 latitude = 3;</code>
     */
    int getLatitude();

    /**
     * <code>required int32 longitude = 4;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required int32 longitude = 4;</code>
     */
    int getLongitude();

    /**
     * <code>required int32 heading = 5;</code>
     */
    boolean hasHeading();
    /**
     * <code>required int32 heading = 5;</code>
     */
    int getHeading();

    /**
     * <code>required int32 altitude = 6;</code>
     */
    boolean hasAltitude();
    /**
     * <code>required int32 altitude = 6;</code>
     */
    int getAltitude();

    /**
     * <code>required int32 speed = 7;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 7;</code>
     */
    int getSpeed();
  }
  /**
   * Protobuf type {@code pnpiot.serializationperf.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pnpiot.serializationperf.Location)
      LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeStamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fixType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              latitude_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              longitude_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              heading_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              altitude_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              speed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pnpiot.serializationperf.LocationProtobuf.internal_static_pnpiot_serializationperf_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pnpiot.serializationperf.LocationProtobuf.internal_static_pnpiot_serializationperf_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pnpiot.serializationperf.LocationProtobuf.Location.class, pnpiot.serializationperf.LocationProtobuf.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timeStamp_;
    /**
     * <code>required int64 timeStamp = 1;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timeStamp = 1;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int FIXTYPE_FIELD_NUMBER = 2;
    private int fixType_;
    /**
     * <code>required int32 fixType = 2;</code>
     */
    public boolean hasFixType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 fixType = 2;</code>
     */
    public int getFixType() {
      return fixType_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private int latitude_;
    /**
     * <code>required int32 latitude = 3;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 latitude = 3;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private int longitude_;
    /**
     * <code>required int32 longitude = 4;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 longitude = 4;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    public static final int HEADING_FIELD_NUMBER = 5;
    private int heading_;
    /**
     * <code>required int32 heading = 5;</code>
     */
    public boolean hasHeading() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 heading = 5;</code>
     */
    public int getHeading() {
      return heading_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 6;
    private int altitude_;
    /**
     * <code>required int32 altitude = 6;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 altitude = 6;</code>
     */
    public int getAltitude() {
      return altitude_;
    }

    public static final int SPEED_FIELD_NUMBER = 7;
    private int speed_;
    /**
     * <code>required int32 speed = 7;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 speed = 7;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    private void initFields() {
      timeStamp_ = 0L;
      fixType_ = 0;
      latitude_ = 0;
      longitude_ = 0;
      heading_ = 0;
      altitude_ = 0;
      speed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFixType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAltitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fixType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, heading_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, altitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, speed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fixType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, heading_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, altitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pnpiot.serializationperf.LocationProtobuf.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pnpiot.serializationperf.LocationProtobuf.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pnpiot.serializationperf.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pnpiot.serializationperf.Location)
        pnpiot.serializationperf.LocationProtobuf.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pnpiot.serializationperf.LocationProtobuf.internal_static_pnpiot_serializationperf_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pnpiot.serializationperf.LocationProtobuf.internal_static_pnpiot_serializationperf_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pnpiot.serializationperf.LocationProtobuf.Location.class, pnpiot.serializationperf.LocationProtobuf.Location.Builder.class);
      }

      // Construct using pnpiot.serializationperf.LocationProtobuf.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fixType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        heading_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        altitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pnpiot.serializationperf.LocationProtobuf.internal_static_pnpiot_serializationperf_Location_descriptor;
      }

      public pnpiot.serializationperf.LocationProtobuf.Location getDefaultInstanceForType() {
        return pnpiot.serializationperf.LocationProtobuf.Location.getDefaultInstance();
      }

      public pnpiot.serializationperf.LocationProtobuf.Location build() {
        pnpiot.serializationperf.LocationProtobuf.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pnpiot.serializationperf.LocationProtobuf.Location buildPartial() {
        pnpiot.serializationperf.LocationProtobuf.Location result = new pnpiot.serializationperf.LocationProtobuf.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fixType_ = fixType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.heading_ = heading_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pnpiot.serializationperf.LocationProtobuf.Location) {
          return mergeFrom((pnpiot.serializationperf.LocationProtobuf.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pnpiot.serializationperf.LocationProtobuf.Location other) {
        if (other == pnpiot.serializationperf.LocationProtobuf.Location.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasFixType()) {
          setFixType(other.getFixType());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasHeading()) {
          setHeading(other.getHeading());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasFixType()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasHeading()) {
          
          return false;
        }
        if (!hasAltitude()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pnpiot.serializationperf.LocationProtobuf.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pnpiot.serializationperf.LocationProtobuf.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timeStamp_ ;
      /**
       * <code>required int64 timeStamp = 1;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timeStamp = 1;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required int64 timeStamp = 1;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStamp = 1;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private int fixType_ ;
      /**
       * <code>required int32 fixType = 2;</code>
       */
      public boolean hasFixType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 fixType = 2;</code>
       */
      public int getFixType() {
        return fixType_;
      }
      /**
       * <code>required int32 fixType = 2;</code>
       */
      public Builder setFixType(int value) {
        bitField0_ |= 0x00000002;
        fixType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fixType = 2;</code>
       */
      public Builder clearFixType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fixType_ = 0;
        onChanged();
        return this;
      }

      private int latitude_ ;
      /**
       * <code>required int32 latitude = 3;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 latitude = 3;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>required int32 latitude = 3;</code>
       */
      public Builder setLatitude(int value) {
        bitField0_ |= 0x00000004;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 latitude = 3;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <code>required int32 longitude = 4;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 longitude = 4;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>required int32 longitude = 4;</code>
       */
      public Builder setLongitude(int value) {
        bitField0_ |= 0x00000008;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 longitude = 4;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0;
        onChanged();
        return this;
      }

      private int heading_ ;
      /**
       * <code>required int32 heading = 5;</code>
       */
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 heading = 5;</code>
       */
      public int getHeading() {
        return heading_;
      }
      /**
       * <code>required int32 heading = 5;</code>
       */
      public Builder setHeading(int value) {
        bitField0_ |= 0x00000010;
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 heading = 5;</code>
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000010);
        heading_ = 0;
        onChanged();
        return this;
      }

      private int altitude_ ;
      /**
       * <code>required int32 altitude = 6;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 altitude = 6;</code>
       */
      public int getAltitude() {
        return altitude_;
      }
      /**
       * <code>required int32 altitude = 6;</code>
       */
      public Builder setAltitude(int value) {
        bitField0_ |= 0x00000020;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 altitude = 6;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        altitude_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>required int32 speed = 7;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 speed = 7;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 7;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000040;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 7;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        speed_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pnpiot.serializationperf.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pnpiot.serializationperf.Location)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pnpiot_serializationperf_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pnpiot_serializationperf_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016location.proto\022\030pnpiot.serializationpe" +
      "rf\"\205\001\n\010Location\022\021\n\ttimeStamp\030\001 \002(\003\022\017\n\007fi" +
      "xType\030\002 \002(\005\022\020\n\010latitude\030\003 \002(\005\022\021\n\tlongitu" +
      "de\030\004 \002(\005\022\017\n\007heading\030\005 \002(\005\022\020\n\010altitude\030\006 " +
      "\002(\005\022\r\n\005speed\030\007 \002(\005B,\n\030pnpiot.serializati" +
      "onperfB\020LocationProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pnpiot_serializationperf_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pnpiot_serializationperf_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pnpiot_serializationperf_Location_descriptor,
        new java.lang.String[] { "TimeStamp", "FixType", "Latitude", "Longitude", "Heading", "Altitude", "Speed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
